CREATE TABLE `aeeaphprunner_audit`(`id` int NOT NULL AUTO_INCREMENT, `datetime` datetime NOT NULL, `ip` varchar(40) NOT NULL, `user` varchar(300) NULL, `table` varchar(300) NULL, `action` varchar(250) NOT NULL, `description` mediumtext NULL, PRIMARY KEY (`id`))CHARACTER SET utf8;
CREATE TABLE `country`(`country_id` varchar(8) NOT NULL, `country` varchar(32) NOT NULL, PRIMARY KEY (`country_id`(8)))CHARACTER SET utf8;
CREATE TABLE `provinces`(`province_id` varchar(8) NOT NULL, `country_id` varchar(8) NOT NULL, `province` varchar(54) NOT NULL, PRIMARY KEY (`province_id`(8)))CHARACTER SET utf8;
CREATE TABLE `reps`(`rep_id` int NOT NULL AUTO_INCREMENT, `firstname` varchar(32) NOT NULL, `lastname` varchar(32) NOT NULL, `passport` varchar(16) NOT NULL, `postbox` varchar(16) NOT NULL, `address` varchar(32) NOT NULL, `city` varchar(32) NOT NULL, `province` varchar(32) NOT NULL, `country` varchar(8) NOT NULL, `postalcode` varchar(8) NOT NULL, `homephone` varchar(16) NOT NULL, `workphone` varchar(16) NOT NULL, `cellphone` varchar(16) NOT NULL, `email` varchar(32) NOT NULL, `birthdate` date NOT NULL, `photo` varchar(30) NULL, `username` varchar(32) NOT NULL, `password` varchar(32) NOT NULL, `pwsalt` varchar(64) NOT NULL, `group` int NOT NULL DEFAULT 0, `created` date NOT NULL, `attempt` int NOT NULL DEFAULT 0, PRIMARY KEY (`rep_id`))CHARACTER SET utf8;
CREATE TABLE `school`(`school_id` int NOT NULL AUTO_INCREMENT, `rep_id` int NOT NULL, `school_name` varchar(64) NOT NULL, `reg_number` varchar(20) NOT NULL, `reg_date` date NOT NULL, `school_type` varchar(32) NOT NULL, `londitude` varchar(16) NULL, `latitude` varchar(16) NULL, `administrator` varchar(54) NULL, `principal` varchar(54) NOT NULL, `postbox` varchar(16) NOT NULL, `address` varchar(32) NOT NULL, `city` varchar(32) NOT NULL, `province` varchar(32) NOT NULL, `postalcode` varchar(8) NOT NULL, `country` varchar(8) NOT NULL, `email` varchar(32) NOT NULL, `school_phone` varchar(16) NULL, `admin_cellphone` varchar(16) NOT NULL, `cresh` int NULL, `grade_r` int NULL, `grade_0` int NULL, `grade_1` int NULL, `grade_2` int NULL, `grade_3` int NULL, `grade_4` int NULL, `grade_5` int NULL, `grade_6` int NULL, `grade_7` int NULL, `grade_8` int NULL, `grade_9` int NULL, `grade_10` int NULL, `grade_11` int NULL, `grade_12` int NULL, `total_students` int NULL, PRIMARY KEY (`school_id`))CHARACTER SET utf8;
CREATE TABLE `school_type`(`type_id` int NOT NULL AUTO_INCREMENT, `school_type` varchar(32) NOT NULL, PRIMARY KEY (`type_id`))CHARACTER SET utf8;
SET FOREIGN_KEY_CHECKS = 0;
INSERT INTO `aeeaphprunner_audit` (`id`,`datetime`,`ip`,`user`,`table`,`action`,`description`) VALUES (1,'2015-05-17 00:23:58','::1','Admin','reps','failed login','');
INSERT INTO `aeeaphprunner_audit` (`id`,`datetime`,`ip`,`user`,`table`,`action`,`description`) VALUES (2,'2015-05-17 00:23:58','::1','Admin','','access','');
SET FOREIGN_KEY_CHECKS = 1;
SET FOREIGN_KEY_CHECKS = 0;
INSERT INTO `country` (`country_id`,`country`) VALUES ('AO','Angola ');
INSERT INTO `country` (`country_id`,`country`) VALUES ('BF','Burkina Faso ');
INSERT INTO `country` (`country_id`,`country`) VALUES ('BI','Burundi ');
INSERT INTO `country` (`country_id`,`country`) VALUES ('BJ','Benin ');
INSERT INTO `country` (`country_id`,`country`) VALUES ('BW','Botswana ');
INSERT INTO `country` (`country_id`,`country`) VALUES ('CD','Democratic Republic of the Congo');
INSERT INTO `country` (`country_id`,`country`) VALUES ('CF','Central African Republic ');
INSERT INTO `country` (`country_id`,`country`) VALUES ('CG','Congo ');
INSERT INTO `country` (`country_id`,`country`) VALUES ('CI','Ivory Coast ');
INSERT INTO `country` (`country_id`,`country`) VALUES ('CM','Cameroon ');
INSERT INTO `country` (`country_id`,`country`) VALUES ('CV','Cape Verde Islands ');
INSERT INTO `country` (`country_id`,`country`) VALUES ('DJ','Djibouti ');
INSERT INTO `country` (`country_id`,`country`) VALUES ('DZ','Algeria ');
INSERT INTO `country` (`country_id`,`country`) VALUES ('EG','Egypt ');
INSERT INTO `country` (`country_id`,`country`) VALUES ('ER','Eritrea ');
INSERT INTO `country` (`country_id`,`country`) VALUES ('ET','Ethiopia ');
INSERT INTO `country` (`country_id`,`country`) VALUES ('GA','Gabon Republic ');
INSERT INTO `country` (`country_id`,`country`) VALUES ('GH','Ghana ');
INSERT INTO `country` (`country_id`,`country`) VALUES ('GM','Gambia ');
INSERT INTO `country` (`country_id`,`country`) VALUES ('GN','Guinea ');
INSERT INTO `country` (`country_id`,`country`) VALUES ('GQ','Equatorial Guinea ');
INSERT INTO `country` (`country_id`,`country`) VALUES ('GW','Guinea-Bissau ');
INSERT INTO `country` (`country_id`,`country`) VALUES ('KE','Kenya ');
INSERT INTO `country` (`country_id`,`country`) VALUES ('KM','Comoros Islands');
INSERT INTO `country` (`country_id`,`country`) VALUES ('LR','Liberia ');
INSERT INTO `country` (`country_id`,`country`) VALUES ('LS','Lesotho ');
INSERT INTO `country` (`country_id`,`country`) VALUES ('LY','Libya ');
INSERT INTO `country` (`country_id`,`country`) VALUES ('MA','Morocco ');
INSERT INTO `country` (`country_id`,`country`) VALUES ('MG','Madagascar ');
INSERT INTO `country` (`country_id`,`country`) VALUES ('ML','Mali Republic ');
INSERT INTO `country` (`country_id`,`country`) VALUES ('MR','Mauritania');
INSERT INTO `country` (`country_id`,`country`) VALUES ('MU','Mauritius ');
INSERT INTO `country` (`country_id`,`country`) VALUES ('MW','Malawi ');
INSERT INTO `country` (`country_id`,`country`) VALUES ('MZ','Mozambique ');
INSERT INTO `country` (`country_id`,`country`) VALUES ('NA','Namibia ');
INSERT INTO `country` (`country_id`,`country`) VALUES ('NE','Niger Republic ');
INSERT INTO `country` (`country_id`,`country`) VALUES ('NG','Nigeria ');
INSERT INTO `country` (`country_id`,`country`) VALUES ('RW','Rwanda ');
INSERT INTO `country` (`country_id`,`country`) VALUES ('SC','Seychelles ');
INSERT INTO `country` (`country_id`,`country`) VALUES ('SD','Sudan ');
INSERT INTO `country` (`country_id`,`country`) VALUES ('SL','Sierra Leone ');
INSERT INTO `country` (`country_id`,`country`) VALUES ('SM','Samali-land');
INSERT INTO `country` (`country_id`,`country`) VALUES ('SN','Senegal Republic ');
INSERT INTO `country` (`country_id`,`country`) VALUES ('SO','Somalia Republic ');
INSERT INTO `country` (`country_id`,`country`) VALUES ('SS','South Sudan ');
INSERT INTO `country` (`country_id`,`country`) VALUES ('SZ','Swaziland ');
INSERT INTO `country` (`country_id`,`country`) VALUES ('TD','Chad Republic ');
INSERT INTO `country` (`country_id`,`country`) VALUES ('TG','Togo ');
INSERT INTO `country` (`country_id`,`country`) VALUES ('TN','Tunisia ');
INSERT INTO `country` (`country_id`,`country`) VALUES ('UG','Uganda ');
INSERT INTO `country` (`country_id`,`country`) VALUES ('ZA','South Africa ');
INSERT INTO `country` (`country_id`,`country`) VALUES ('ZM','Zambia ');
INSERT INTO `country` (`country_id`,`country`) VALUES ('ZW','Zimbabwe ');
SET FOREIGN_KEY_CHECKS = 1;
SET FOREIGN_KEY_CHECKS = 0;
INSERT INTO `reps` (`rep_id`,`firstname`,`lastname`,`passport`,`postbox`,`address`,`city`,`province`,`country`,`postalcode`,`homephone`,`workphone`,`cellphone`,`email`,`birthdate`,`photo`,`username`,`password`,`pwsalt`,`group`,`created`,`attempt`) VALUES (1,'Adam','Apple','1234567898025','1026','1044 Main street','Shayandima','Limpopo','ZA','0945','','015 123 4567','082 547 8965','adam@apple.co.za','2015-04-01','52601800_1430235772.png','Admin','admin123!','',-1,'2015-05-16',0);
INSERT INTO `reps` (`rep_id`,`firstname`,`lastname`,`passport`,`postbox`,`address`,`city`,`province`,`country`,`postalcode`,`homephone`,`workphone`,`cellphone`,`email`,`birthdate`,`photo`,`username`,`password`,`pwsalt`,`group`,`created`,`attempt`) VALUES (2,'Ben','Bahuna','zm7899654','245688','Area 45','Hlelui','','Zimbabwe','2145','','','','ban@bahana.zm','0000-00-00',NULL,'ben','tentun123!','',0,'0000-00-00',0);
INSERT INTO `reps` (`rep_id`,`firstname`,`lastname`,`passport`,`postbox`,`address`,`city`,`province`,`country`,`postalcode`,`homephone`,`workphone`,`cellphone`,`email`,`birthdate`,`photo`,`username`,`password`,`pwsalt`,`group`,`created`,`attempt`) VALUES (3,'Caryn','Cummings','','','','','','Mozambiq','','','','','ccummings@anywhere.mz','0000-00-00',NULL,'CCmings','caryn123!','',0,'2015-05-16',0);
SET FOREIGN_KEY_CHECKS = 1;
SET FOREIGN_KEY_CHECKS = 0;
INSERT INTO `school` (`school_id`,`rep_id`,`school_name`,`reg_number`,`reg_date`,`school_type`,`londitude`,`latitude`,`administrator`,`principal`,`postbox`,`address`,`city`,`province`,`postalcode`,`country`,`email`,`school_phone`,`admin_cellphone`,`cresh`,`grade_r`,`grade_0`,`grade_1`,`grade_2`,`grade_3`,`grade_4`,`grade_5`,`grade_6`,`grade_7`,`grade_8`,`grade_9`,`grade_10`,`grade_11`,`grade_12`,`total_students`) VALUES (1,1,'Shayandima School of Tomorrow','ABC 12345','2015-04-01','3',NULL,NULL,'Hazel','Palmer','1028','1044 Main street','Shayandima','Limpopo','0945','ZA','admin@buildthenations.org','015 123 4567','082 784 1236',45,23,25,24,52,23,45,32,27,16,18,12,8,2,1,NULL);
SET FOREIGN_KEY_CHECKS = 1;
SET FOREIGN_KEY_CHECKS = 0;
INSERT INTO `school_type` (`type_id`,`school_type`) VALUES (1,'Home School');
INSERT INTO `school_type` (`type_id`,`school_type`) VALUES (2,'Home School Academy');
INSERT INTO `school_type` (`type_id`,`school_type`) VALUES (3,'Mission School');
INSERT INTO `school_type` (`type_id`,`school_type`) VALUES (4,'Pre-School');
INSERT INTO `school_type` (`type_id`,`school_type`) VALUES (5,'Primary School');
INSERT INTO `school_type` (`type_id`,`school_type`) VALUES (6,'High / Secondary School');
INSERT INTO `school_type` (`type_id`,`school_type`) VALUES (7,'Full School');
INSERT INTO `school_type` (`type_id`,`school_type`) VALUES (8,'Private School');
SET FOREIGN_KEY_CHECKS = 1;
