<?php
$dalTableschool = array();
$dalTableschool["school_id"] = array("type"=>3,"varname"=>"school_id");
$dalTableschool["rep_id"] = array("type"=>3,"varname"=>"rep_id");
$dalTableschool["school_name"] = array("type"=>200,"varname"=>"school_name");
$dalTableschool["reg_number"] = array("type"=>200,"varname"=>"reg_number");
$dalTableschool["reg_date"] = array("type"=>7,"varname"=>"reg_date");
$dalTableschool["school_type"] = array("type"=>200,"varname"=>"school_type");
$dalTableschool["londitude"] = array("type"=>200,"varname"=>"londitude");
$dalTableschool["latitude"] = array("type"=>200,"varname"=>"latitude");
$dalTableschool["administrator"] = array("type"=>200,"varname"=>"administrator");
$dalTableschool["principal"] = array("type"=>200,"varname"=>"principal");
$dalTableschool["postbox"] = array("type"=>200,"varname"=>"postbox");
$dalTableschool["address"] = array("type"=>200,"varname"=>"address");
$dalTableschool["city"] = array("type"=>200,"varname"=>"city");
$dalTableschool["state_province"] = array("type"=>200,"varname"=>"state_province");
$dalTableschool["zip_postalcode"] = array("type"=>200,"varname"=>"zip_postalcode");
$dalTableschool["country"] = array("type"=>200,"varname"=>"country");
$dalTableschool["email"] = array("type"=>200,"varname"=>"email");
$dalTableschool["school_phone"] = array("type"=>200,"varname"=>"school_phone");
$dalTableschool["admin_cellphone"] = array("type"=>200,"varname"=>"admin_cellphone");
$dalTableschool["cresh"] = array("type"=>3,"varname"=>"cresh");
$dalTableschool["grade_r"] = array("type"=>3,"varname"=>"grade_r");
$dalTableschool["grade_0"] = array("type"=>3,"varname"=>"grade_0");
$dalTableschool["grade_1"] = array("type"=>3,"varname"=>"grade_1");
$dalTableschool["grade_2"] = array("type"=>3,"varname"=>"grade_2");
$dalTableschool["grade_3"] = array("type"=>3,"varname"=>"grade_3");
$dalTableschool["grade_4"] = array("type"=>3,"varname"=>"grade_4");
$dalTableschool["grade_5"] = array("type"=>3,"varname"=>"grade_5");
$dalTableschool["grade_6"] = array("type"=>3,"varname"=>"grade_6");
$dalTableschool["grade_7"] = array("type"=>3,"varname"=>"grade_7");
$dalTableschool["grade_8"] = array("type"=>3,"varname"=>"grade_8");
$dalTableschool["grade_9"] = array("type"=>3,"varname"=>"grade_9");
$dalTableschool["grade_10"] = array("type"=>3,"varname"=>"grade_10");
$dalTableschool["grade_11"] = array("type"=>3,"varname"=>"grade_11");
$dalTableschool["grade_12"] = array("type"=>3,"varname"=>"grade_12");
$dalTableschool["total_students"] = array("type"=>3,"varname"=>"total_students");
	$dalTableschool["school_id"]["key"]=true;

$dal_info["aeeaphprunner_at_localhost__school"] = &$dalTableschool;
?>